spring:
  config:
    import: optional:classpath:application-secret.yml

  datasource:
    url: jdbc:postgresql://svc.sel5.cloudtype.app:30502/postgres
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      idle-timeout: 10000
      max-lifetime: 20000

  jpa:
    hibernate:
      ddl-auto: update # create / validate로 수정 가능
    show-sql: false
    properties:
      hibernate:
        format_sql: true

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: https://keungdori-frontend-git-feat-login-park-junhyeongs-projects.vercel.app/oauth/callback

jwt:
  access-token-expiration: 86400000 # 1일
  refresh-token-expiration: 1209600000 # 14일
  secret: ${JWT_SECRET}